name: Silveran
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
configs:
  Debug: debug
  Release: release
packages:
  SilveranKit:
    path: SilveranKit
targets:
  Silveran Reader (macOS):
    type: application
    platform: macOS
    supportedDestinations: [macOS]
    productName: "Silveran Reader"
    settings:
      base:
        MACOSX_DEPLOYMENT_TARGET: 14.0
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: XCodeWrapper/SilveranReaderMac.entitlements
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: 9CJ7KG7UKQ
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.books
        INFOPLIST_KEY_NSLocalNetworkUsageDescription: "Silveran Reader needs local network access to connect to your Storyteller server."
        MARKETING_VERSION: 1.0
        PRODUCT_BUNDLE_IDENTIFIER: com.kyonifer.SilveranReader
        #INFOPLIST_KEY_CFBundleDisplayName: Silveran Reader
        #INFOPLIST_KEY_CFBundleName: Silveran Reader
        # Unknown why this redundant definition is needed for XCode to honor the app name
        PRODUCT_NAME: Silveran Reader
        #SWIFT_UPCOMING_FEATURE_NONSENDING_NONISOLATING_BY_DEFAULT: YES
        SWIFT_VERSION: 6.2
    sources:
      - path: XCodeWrapper
        excludes:
          - "**/*.entitlements"
          - "**/.DS_Store"
          - "WebResources/"
          - "Assets.xcassets/"
          - "project.yml"
          - "PrivacyInfo.xcprivacy"
      - path: XCodeWrapper/Assets.xcassets
        type: assetcatalog
      - path: XCodeWrapper/PrivacyInfo.xcprivacy
        buildPhase: resources
      - path: XCodeWrapper/WebResources
        type: folder
        buildPhase: resources
      - path: extern/foliate-js
        type: folder
        buildPhase: resources
        excludes:
          - "tests/"
          - ".github/"
          - "rollup/"
          - "*.md"
          - "package.json"
          - "package-lock.json"
          - "eslint.config.js"
          - "rollup.config.js"
          - ".git*"
    dependencies:
      - package: SilveranKit
        product: SilveranKitMacApp
  Silveran Reader (iOS):
    type: application
    platform: iOS
    productName: "Silveran Reader"
    settings:
      base:
        IPHONEOS_DEPLOYMENT_TARGET: 17.0
        CODE_SIGN_ENTITLEMENTS: XCodeWrapper/SilveranReaderIos.entitlements
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: 9CJ7KG7UKQ
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: XCodeWrapper/Info-iOS.plist
        MARKETING_VERSION: 1.0
        PRODUCT_BUNDLE_IDENTIFIER: com.kyonifer.SilveranReader
        #INFOPLIST_KEY_CFBundleDisplayName: Silveran Reader
        #INFOPLIST_KEY_CFBundleName: Silveran Reader
        PRODUCT_NAME: Silveran Reader
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        #SWIFT_UPCOMING_FEATURE_NONSENDING_NONISOLATING_BY_DEFAULT: YES
        SWIFT_VERSION: 6.2
    info:
      path: XCodeWrapper/Info-iOS.plist
      properties:
        CFBundleName: "Silveran Reader"
        CFBundleDisplayName: "Silveran Reader"
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundlePackageType: "$(PRODUCT_BUNDLE_PACKAGE_TYPE)"
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        LSApplicationCategoryType: "public.app-category.books"
        NSLocalNetworkUsageDescription: "Silveran Reader needs local network access to connect to your Storyteller server."
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIBackgroundModes:
          - audio
    sources:
      - path: XCodeWrapper
        excludes:
          - "**/*.entitlements"
          - "**/.DS_Store"
          - "WebResources/"
          - "Assets.xcassets/"
          - "project.yml"
          - "PrivacyInfo.xcprivacy"
      - path: XCodeWrapper/Assets.xcassets
        type: assetcatalog
      - path: XCodeWrapper/PrivacyInfo.xcprivacy
        buildPhase: resources
      - path: XCodeWrapper/WebResources
        type: folder
        buildPhase: resources
      - path: extern/foliate-js
        type: folder
        buildPhase: resources
        excludes:
          - "tests/"
          - ".github/"
          - "rollup/"
          - "*.md"
          - "package.json"
          - "package-lock.json"
          - "eslint.config.js"
          - "rollup.config.js"
          - ".git*"
    dependencies:
      - package: SilveranKit
        product: SilveranKitiOSApp
schemes:
  "Silveran Reader (macOS)":
    shared: true
    build:
      targets:
        "Silveran Reader (macOS)": all
    run:
      config: Debug
      executable: "Silveran Reader (macOS)"
    test:
      config: Debug
      targets: []
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  "Silveran Reader (iOS)":
    shared: true
    build:
      targets:
        "Silveran Reader (iOS)": all
    run:
      config: Debug
      executable: "Silveran Reader (iOS)"
    test:
      config: Debug
      targets: []
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
