#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")" && pwd)"
cd "${SCRIPT_DIR}/.."

swift build --target SilveranAppleKit
swift build --target SilveranAppleKit \
      --sdk $(xcrun --sdk iphonesimulator --show-sdk-path) \
      --triple arm64-apple-ios18.0-simulator
