#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")" && pwd)"
cd "${SCRIPT_DIR}/.."

xcodebuild -project Silveran.xcodeproj \
    -scheme "Silveran Reader (watchOS)" \
    -configuration Debug \
    -destination 'platform=watchOS Simulator,id=08EC1854-5E75-4159-B897-0C37B6FAC2CD' \
    -derivedDataPath .buildWatch build | xcbeautify
