import { debugLog } from "./DebugConfig.js";

/**
 * BookLoader - Loads an extracted EPUB from a directory
 *
 * When a book is loaded, automatically passes it to FoliateManager
 */
export default class BookLoader {
  #foliateManager;

  constructor(foliateManager) {
    this.#foliateManager = foliateManager;
    debugLog("BookLoader", "Initialized");
  }

  /**
   * Load and open a book from a directory
   * Non-async wrapper for Swift to call - kicks off loading and returns immediately
   */
  openBookFromDirectory(dirPath) {
    debugLog("BookLoader", "openBookFromDirectory() called with path:", dirPath);
    this.#loadBookFromDirectory(dirPath)
      .then(book => this.#foliateManager.open(book))
      .catch(err => console.error("[BookLoader] Failed to load book from directory:", err));
  }

  /**
   * Create a custom loader for a directory (extracted EPUB)
   */
  async #makeCustomDirectoryLoader(dirPath) {
  debugLog("BookLoader", "Creating directory loader for:", dirPath);

  if (!dirPath.endsWith('/')) {
    dirPath = dirPath + '/';
  }

  const decoder = new TextDecoder();

  // Load sizes manifest generated by Swift during extraction
  let sizeMap = {};
  try {
    const sizesUrl = new URL('_sizes.json', `file://${dirPath}`);
    const response = await fetch(sizesUrl);
    if (response.ok || response.status === 0) {
      sizeMap = await response.json();
      debugLog("BookLoader", "Loaded sizes manifest:", Object.keys(sizeMap).length, "entries");
    }
  } catch (err) {
    console.warn("[BookLoader] Could not load _sizes.json:", err);
  }

  let healthCheckFile = null;

  async function fetchFileAsBlob(filename) {
    let url;
    try {
      url = new URL(filename, `file://${dirPath}`);
      debugLog("BookLoader", "Fetching file:", url.href);
      const response = await fetch(url);
      if (!response.ok && response.status !== 0) {
        console.error("[BookLoader] Failed to fetch", filename, "status:", response.status);
        await reportFetchFailure(filename, url.href, `HTTP status ${response.status}`);
        return null;
      }
      const blob = await response.blob();
      if (!healthCheckFile && blob && blob.size > 0) {
        healthCheckFile = { filename, href: url.href };
      }
      return blob;
    } catch (err) {
      console.error("[BookLoader] Error fetching", filename, err);
      console.error("[BookLoader] Error name:", err?.name, "message:", err?.message, "cause:", err?.cause);
      await reportFetchFailure(filename, url?.href ?? filename, `${err?.name}: ${err?.message}`);
      return null;
    }
  }

  async function reportFetchFailure(filename, fullUrl, errorMessage) {
    try {
      const filePath = fullUrl.startsWith("file://")
        ? decodeURIComponent(fullUrl.replace("file://", ""))
        : filename;

      window.webkit?.messageHandlers?.FileAccessDiagnostic?.postMessage({
        filePath: filePath,
        errorMessage: errorMessage,
      });

      if (healthCheckFile) {
        debugLog("BookLoader", "Running health check fetch on previously-loaded file:", healthCheckFile.filename);
        try {
          const checkResponse = await fetch(healthCheckFile.href);
          const checkOk = checkResponse.ok || checkResponse.status === 0;
          if (checkOk) {
            const checkBlob = await checkResponse.blob();
            debugLog("BookLoader", "Health check PASSED - fetched", checkBlob.size, "bytes. Failure is specific to:", filename);
          } else {
            console.error("[BookLoader] Health check FAILED - status:", checkResponse.status, "- file:// access may be systemically broken");
          }
        } catch (healthErr) {
          console.error("[BookLoader] Health check FAILED with error:", healthErr?.name, healthErr?.message, "- file:// access is systemically broken");
        }
      } else {
        debugLog("BookLoader", "No health check file available (no previous successful fetch)");
      }
    } catch (diagErr) {
      console.error("[BookLoader] Diagnostic reporting itself failed:", diagErr);
    }
  }

  async function loadText(filename) {
    const blob = await fetchFileAsBlob(filename);
    if (!blob) return null;
    const buffer = await blob.arrayBuffer();
    return decoder.decode(buffer);
  }

  async function loadBlob(filename) {
    return await fetchFileAsBlob(filename);
  }

  function getSize(filename) {
    return sizeMap[filename] ?? 0;
  }

  return { loadText, loadBlob, getSize };
}

  /**
   * Load a book from a directory (extracted EPUB)
   */
  async #loadBookFromDirectory(dirPath) {
  debugLog("BookLoader", "Loading book from directory:", dirPath);
  try {
    debugLog("BookLoader", "Creating custom loader...");
    const loader = await this.#makeCustomDirectoryLoader(dirPath);

    debugLog("BookLoader", "Importing EPUB module...");
    const { EPUB } = await import('./foliate-js/epub.js');

    debugLog("BookLoader", "Creating EPUB instance...");
    const epub = new EPUB(loader);

    debugLog("BookLoader", "Initializing EPUB...");
    const book = await epub.init();

    debugLog("BookLoader", "Book loaded successfully from directory");
    return book;
  } catch (err) {
    console.error("[BookLoader] Error loading book from directory:", err);
    console.error("[BookLoader] Error stack:", err.stack);
    throw err;
  }
}
}
